# Generated by Django 3.2.6 on 2021-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAlumno', models.IntegerField(unique=True)),
                ('nombreAlumno', models.TextField(default='', max_length=60)),
                ('apellidoAlumno', models.TextField(default='', max_length=80)),
                ('dniAlumno', models.CharField(max_length=8, unique=True)),
                ('fechanacAlumno', models.DateField()),
                ('edadAlumno', models.IntegerField()),
                ('gradoAlumno', models.TextField(default='', max_length=20)),
                ('seccionAlumno', models.CharField(default='', max_length=1)),
                ('sexoAlumno', models.CharField(max_length=1)),
            ],
        ),
    ]
